import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Loading from "react-loading";
import styles from "../styles/Home.module.css";
import { HomeCardProps } from "../types";
import { CardDataList } from "../utils/constant";

const HomeCard = ({ title, desc, url, openNewTag = true }: HomeCardProps) => {
    const [loading, setLoading] = useState(false);
    const isA = ["http", "https"].includes(url.split(":")[0]);
    if (isA) {
        return (
            <a href={url} target={openNewTag ? "_blank" : ""} rel="noreferrer">
                <div className={styles.card}>
                    <>
                        <h2>{title} &rarr;</h2>
                        <p>{desc}</p>
                    </>
                </div>
            </a>
        );
    }
    return (
        <div className="relative">
            {loading && (
                <Loading
                    type="spinningBubbles"
                    color="black"
                    className="absolute m-auto top-0 right-0 left-0 bottom-0 w-full h-ful"
                />
            )}
            <Link href={url} passHref>
                <div className={styles.card} onClick={() => setLoading(true)}>
                    <>
                        <h2>{title} &rarr;</h2>
                        <p>{desc}</p>
                    </>
                </div>
            </Link>
        </div>
    );
};

const Home: NextPage = () => {
    return (
        <div className="py-8 px-8">
            <Head>
                <title>Toys</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="min-h-screen py-16 px-0 flex-1 flex flex-col justify-center items-center">
                <h1 className="text-center m-0 text-6xl">
                    Welcome to{" "}
                    <span className="text-blue-500">
                        <a
                            href="https://github.com/SHUAXINDIARY/Toys"
                            target="_blank"
                            rel="noreferrer"
                            className="hover:underline">
                            My Toys Space!
                        </a>
                    </span>
                </h1>
                <div className="text-center my-16 mx-0 text-2xl">
                    <code className="bg-gray-50 dark:bg-slate-600 rounded-[5px] p-3 text-xl font-next">
                        Just for fun
                    </code>
                </div>
                <div className="flex items-center justify-center flex-wrap max-w-[800px]">
                    {CardDataList.map((item) => {
                        return <HomeCard key={item.url} {...item} />;
                    })}
                </div>
            </main>
            <footer className="flex flex-1 pt-8 px-0 border-t-2 border-solid border-[#eaeaea] justify-center items-center">
                <a
                    href="https://github.com/SHUAXINDIARY"
                    target="_blank"
                    rel="noreferrer"
                    className="mr-2 text-xl text-blue-500">
                    Find Me
                </a>
            </footer>
        </div>
    );
};

export default Home;
