import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Toys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a
            href="https:/blog.shuaxindiary.cn"
            target="_blank"
            rel="noreferrer"
          >
            My Toys Space!
          </a>
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>Just for fun</code>
        </p>

        <div className={styles.grid}>
          <Link href="/resume" passHref>
            <div className={styles.card}>
              <>
                <h2>Github Resume &rarr;</h2>
                <p>Generate resume by your github message.</p>
              </>
            </div>
          </Link>

          <Link href="/couplet" passHref>
            <div className={styles.card}>
              <>
                <h2>Couplet &rarr;</h2>
                <p>Happy New Year !</p>
              </>
            </div>
          </Link>

          <a
            href="https://blog.shuaxindiary.cn"
            target="_blank"
            rel="noreferrer"
          >
            <div className={styles.card}>
              <h2>Blog &rarr;</h2>
              <p>Record Note.</p>
            </div>
          </a>

          <a href="https://github.com/SHUAXINDIARY">
            <div className={styles.card}>
              <h2>Github &rarr;</h2>
            </div>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
